import React from 'react';
import Link from 'next/link';
import { Card } from '@/components/ui/Card';

export const metadata = {
  title: 'Terms of Service - AI Visibility Checker',
  description: 'Terms of Service for AI Visibility Checker',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-pageBg text-primaryText flex flex-col justify-between">
      <header className="w-full max-w-4xl mx-auto px-4 py-6 sm:py-8">
        <Link href="/" className="font-display text-xl sm:text-2xl font-bold tracking-tight text-primaryText hover:opacity-90">
          AI Visibility Checker
        </Link>
      </header>

      <main className="w-full max-w-3xl mx-auto px-4 py-8 sm:py-12 flex-1">
        <Card className="space-y-6">
          <h1 className="font-display text-2xl sm:text-3xl font-bold text-primaryText">Terms of Service</h1>
          <p className="text-sm text-mutedText">Last updated: August 2, 2026</p>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-primaryText">1. Free Scan Usage Limits</h2>
            <p className="text-sm text-slate-300 leading-relaxed">
              Our free AI Visibility Checker allows 1 free scan request per domain per 30-day period, as well as per-network rate limiting. Requests exceeding these parameters may be cached or throttled.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-primaryText">2. No Warranty on AI Content</h2>
            <p className="text-sm text-slate-300 leading-relaxed">
              Reports and scores are generated by third-party artificial intelligence models. We make no representations or warranties regarding the accuracy, completeness, or stability of AI-generated responses.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-primaryText">3. Prohibited Use</h2>
            <p className="text-sm text-slate-300 leading-relaxed">
              You agree not to abuse, automate, scrape, or perform unauthorized mass querying of the service. We reserve the right to block IPs or domains engaging in abusive or unauthorized automated activity.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-primaryText">4. Contact Information</h2>
            <p className="text-sm text-slate-300 leading-relaxed">
              AI Visibility Checker is operated by <span className="text-accent">[COMPANY_NAME]</span>. For questions about these terms, reach us at <span className="text-accent">[SUPPORT_EMAIL]</span>.
            </p>
          </section>

          <div className="pt-4 border-t border-slate-800">
            <Link href="/" className="text-xs text-accent hover:underline">
              ← Back to Home
            </Link>
          </div>
        </Card>
      </main>

      <footer className="w-full max-w-4xl mx-auto px-4 py-8 border-t border-[#6B7280]/20 text-center text-xs text-mutedText flex flex-col sm:flex-row items-center justify-between gap-4">
        <span>© {new Date().getFullYear()} AI Visibility Checker. All rights reserved.</span>
        <div className="flex items-center gap-4">
          <Link href="/privacy" className="hover:text-primaryText transition-colors">
            Privacy Policy
          </Link>
          <Link href="/terms" className="hover:text-primaryText transition-colors">
            Terms of Service
          </Link>
        </div>
      </footer>
    </div>
  );
}
